### ISSUE TITLE
Failing to import module

### ISSUE THREAD

**Issue by erasmas** [toxicphreAK/python-docx-ng#26]
Hi, thank you for bringing `python-docx` back to life!

I'm trying to use `python-docx-ng` but a basic import of `from docx import Document` fails for me. Am I missing something here?

STR:

```
python -m venv .venv
source .venv/bin/activate
echo 'python-docx-ng' > requirements.txt
pip3 install -r requirements.txt
```

```
❯ python3
Python 3.10.11 (main, May 10 2023, 11:30:20) [Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from docx import Document
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/erasmas/docx-ng/.venv/lib/python3.10/site-packages/docx/__init__.py", line 3, in <module>
    from docx.api import Document  # noqa
  File "/Users/erasmas/docx-ng/.venv/lib/python3.10/site-packages/docx/api.py", line 14, in <module>
    from docx.package import Package
  File "/Users/erasmas/docx-ng/.venv/lib/python3.10/site-packages/docx/package.py", line 9, in <module>
    from docx.opc.package import OpcPackage
  File "/Users/erasmas/docx-ng/.venv/lib/python3.10/site-packages/docx/opc/package.py", line 9, in <module>
    from docx.opc.part import PartFactory
  File "/Users/erasmas/docx-ng/.venv/lib/python3.10/site-packages/docx/opc/part.py", line 13, in <module>
    from ..oxml import parse_xml
  File "/Users/erasmas/docx-ng/.venv/lib/python3.10/site-packages/docx/oxml/__init__.py", line 334, in <module>
    from .comment import CT_Comments,CT_Com, CT_CRE, CT_CRS, CT_CRef
  File "/Users/erasmas/docx-ng/.venv/lib/python3.10/site-packages/docx/oxml/comment.py", line 8, in <module>
    from ..text.paragraph import Paragraph
  File "/Users/erasmas/docx-ng/.venv/lib/python3.10/site-packages/docx/text/paragraph.py", line 13, in <module>
    from .run import Run
  File "/Users/erasmas/docx-ng/.venv/lib/python3.10/site-packages/docx/text/run.py", line 11, in <module>
    from docx.opc.part import PackURI, Part
ImportError: cannot import name 'PackURI' from partially initialized module 'docx.opc.part' (most likely due to a circular import) (/Users/erasmas/docx-ng/.venv/lib/python3.10/site-packages/docx/opc/part.py)
```

**Comment by jgrimard** [comment]
I am getting this same error starting with python-docx-ng==0.9.4.   0.9.3 was fine.
If you uninstall the latest version and then install with `pip install python-docx-ng==0.9.3` everything works fine again.

**Comment by jgrimard** [comment]
@toxicphreAK 
Why are we importing PackURI from docx.opc.part in docx/text/run.py? I'm guessing this is what is causing the error.
`from docx.opc.part import PackURI, Part`

I'm guessing it should be imported from docx.opc.packuri
```
from docx.opc.packuri import PackURI
from docx.opc.part import Part
```

https://github.com/toxicphreAK/python-docx-ng/blob/39476c9419b33dc854ba8817f2c90836709f17b3/docx/text/run.py#L11C40-L11C40

**Comment by toxicphreAK** [comment]
> @toxicphreAK Why are we importing PackURI from docx.opc.part in docx/text/run.py? I'm guessing this is what is causing the error. `from docx.opc.part import PackURI, Part`
> 
> I'm guessing it should be imported from docx.opc.packuri
> 
> ```
> from docx.opc.packuri import PackURI
> from docx.opc.part import Part
> ```
> 
> https://github.com/toxicphreAK/python-docx-ng/blob/39476c9419b33dc854ba8817f2c90836709f17b3/docx/text/run.py#L11C40-L11C40

Thanks for your help and contribution!
